### ISSUE TITLE
Visual Studio Dependency

### ISSUE THREAD

**Issue by scottkuhl** [pengweiqhca/Xunit.DependencyInjection#71]
**Describe the bug**
After updating from version 8.5.0 to 8.6.0 our build server started failing.

error CS8032: An instance of analyzer Xunit.DependencyInjection.AnaIyzer.XunitDependencyInjectionAnaIyzer cannot be created from Xunit.Dependencylnjection.Analyzer.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' . The system cannot find the file specified.

We were able to fix it by updating the version of Visual Studio on the server from 17.0.4 to 17.3.6.

**To Reproduce**

1. Install an older version of Visual Studio 2022 (17.0.4 for sure has the issue).
2. Add 8.6.0 NuGet package to a project.
3. Build the solution.

**Expected behavior**
The NuGet package should include all the dependencies it expects and not rely on a specific version of Visual Studio 2022.

**Additional context**
There is no version 4.3.0.0 available as a NuGet package, only 4.3.1.

**Comment by pengweiqhca** [comment]
It Dependency the latest visual studio 2022 version. (My visual studio version is 17.3.6)

**Comment by scottkuhl** [comment]
Yes that is the issue.  The package should not have a dependency on a specific version of Visual Studio.  Can you include the packages it needs as a dependency in the package instead of relying on a version of Visual Studio?

**Comment by pengweiqhca** [comment]
I has downgraded the dependency version in 8.6..1
